# shu ju ku pei zhi wen jian
db.mysql.driver=com.mysql.cj.jdbc.Driver
#MySQL8的网上搜索（驱动，连接串）
#url: jdbc:mysql://localhost:3306/yinliu?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#driver: com.mysql.cj.jdbc.Driver
#localhost(服务器的IP，localhost本地服务器):3306（mysql端口号）/shirodb（数据库名）
#连接串
db.mysql.url=jdbc:mysql://localhost:3306/angongye?allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#数据库的用户名
db.mysql.username=root
#数据库的密码
db.mysql.password=ok